#!/bin/bash

# Set the resource directory
export ARGOSINSTALLDIR=/usr/share/argos2

# Set the library path
if [ -n "${LD_LIBRARY_PATH}" ]
then
    LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/lib/argos2
else
    LD_LIBRARY_PATH=/usr/lib/argos2
fi
export LD_LIBRARY_PATH

# Execute argos with bash internal command exec, which replaces
# the script with the argos executable. In this way, there is
# only one PID and the return value is handled correctly.
exec argos "$@"
